Clients/TAuth.ResourceClient/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TAuth.ResourceClient.Pages
{
    public class AccessDeniedModel : PageModel
    {
        [FromQuery]
        public string ReturnUrl { get; set; }

        public IActionResult OnGet()
        {
            var hasAccessDeniedFlag = HttpContext.Session.GetInt32("AccessDenied") == 1;

            if (!hasAccessDeniedFlag) return LocalRedirect("/");

            HttpContext.Session.Remove("AccessDenied");

            return Page();
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TAuth.Resource.Cross;

namespace TAuth.ResourceClient.Pages
{
    [Authorize(Roles = RoleNames.Administrator)]
    public class AdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using TAuth.Resource.Cross.Models.Resource;
using TAuth.ResourceClient.Services;

namespace TAuth.ResourceClient.Pages
{
    public class CreateModel : PageModel
    {
        private readonly IResourceService _resourceService;

        public CreateModel(IResourceService resourceService)
        {
            _resourceService = resourceService;
        }

        [BindProperty]
        public CreateResourceModel RequestModel { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var id = await _resourceService.CreateAsync(RequestModel);

            return RedirectToPage("/Index");
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TAuth.ResourceClient.Exceptions;

namespace TAuth.ResourceClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet() => HandleError();

        public IActionResult OnPost() => HandleError();

        private IActionResult HandleError()
        {
            var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerFeature>();
            var ex = exceptionFeature?.Error;

            if (ex is HttpException httpEx)
            {
                if (httpEx.Response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    return Challenge();

                if (httpEx.Response.StatusCode == System.Net.HttpStatusCode.Forbidden)
                    return Forbid();
            }

            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return Page();
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using TAuth.Resource.Cross.Models.Resource;
using TAuth.ResourceClient.Auth.Policies;
using TAuth.ResourceClient.Services;

namespace TAuth.ResourceClient.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IResourceService _resourceService;
        private readonly IAuthorizationService _authorizationService;

        public IndexModel(ILogger<IndexModel> logger,
            IResourceService resourceService,
            IAuthorizationService authorizationService)
        {
            _logger = logger;
            _resourceService = resourceService;
            _authorizationService = authorizationService;
        }

        public IEnumerable<ResourceListItemModel> ResourceList { get; set; }
        public bool CanCreateResource { get; set; }

        public async Task<IActionResult> OnGet()
        {
            await DebugIdentity();

            ResourceList = await _resourceService.GetAsync();
            CanCreateResource = (await _authorizationService.AuthorizeAsync(User, PolicyNames.Resource.CanCreateResource)).Succeeded;

            return Page();
        }

        public async Task<IActionResult> OnGetDeleteAsync([FromQuery] int id)
        {
            await _resourceService.DeleteAsync(id);

            return RedirectToPage("/Index");
        }

        private async Task DebugIdentity()
        {
            var idToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);
            var accessToken = await HttpContext.GetUserAccessTokenAsync();
            var refreshToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken);

            Console.WriteLine(refreshToken);
            Debug.WriteLine($"IdToken: {idToken}");

            foreach (var claim in User.Claims)
            {
                Debug.WriteLine($"Claim: {claim.Type} - {claim.Value}");
            }
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace TAuth.ResourceClient.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task OnGet()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }
    }
}

Clients/TAuth.ResourceClient/Pages/Profile.cshtml.cs
using IdentityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Linq;
using System.Threading.Tasks;
using TAuth.ResourceClient.Auth.Policies;
using TAuth.ResourceClient.Services;

namespace TAuth.ResourceClient.Pages
{
    [Authorize(PolicyNames.EmailVerified)]
    public class ProfileModel : PageModel
    {
        private readonly IIdentityService _identityService;

        public ProfileModel(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        public string Address { get; set; } = "Unknown";
        public string FullName { get; set; }

        public async Task OnGetAsync()
        {
            var userInfo = await _identityService.GetUserInfoAsync();

            FullName = userInfo.FirstOrDefault(o => o.Type == JwtClaimTypes.Name)?.Value;

            var addrVal = userInfo.FirstOrDefault(o => o.Type == JwtClaimTypes.Address)?.Value;
            if (!string.IsNullOrWhiteSpace(addrVal))
            {
                var addressObj = JsonConvert.DeserializeAnonymousType(addrVal, new
                {
                    street_address = "",
                    locality = "",
                    postal_code = 0,
                    country = ""
                });

                Address = string.Join(", ", addressObj.street_address, addressObj.locality, $"{addressObj.postal_code}", addressObj.country);
            }
        }
    }
}

Clients/TAuth.ResourceClient/Pages/AccessDenied.cshtml
@page
@model TAuth.ResourceClient.Pages.AccessDeniedModel
@{
    ViewData["Title"] = "Access Denied";
}

<div class="text-center">
    <h1 class="display-4 text-danger">Access Denied</h1>
</div>

Clients/TAuth.ResourceClient/Pages/Admin.cshtml
@page
@model TAuth.ResourceClient.Pages.AdminModel
@{
    ViewData["Title"] = "Admin";
}

<div class="text-center">
    <h1 class="display-4">Admin area</h1>
</div>

Clients/TAuth.ResourceClient/Pages/Create.cshtml
@page
@model TAuth.ResourceClient.Pages.CreateModel
@{
    ViewData["Title"] = "Create Resource";
}

<div class="text-center">
    <h1 class="display-4">Create Resource</h1>
</div>

<div class="container">
    <form role="form" method="post">
        <div class="form-group">
            <label for="resource-name">Name</label>
            <input type="text" class="form-control" id="resource-name" asp-for="@Model.RequestModel.Name" required />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Clients/TAuth.ResourceClient/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="container">
    <div class="row mb-1">
        <div class="col-12">
            @if (Model.CanCreateResource)
            {
                <a asp-area="" asp-page="/Create" class="btn btn-info float-right">
                    Create
                </a>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead class="thead-light">
                    <tr class="d-table-row">
                        <th class="d-table-cell">Id</th>
                        <th class="d-table-cell">Name</th>
                        <th class="d-table-cell">Actions</th>
                    </tr>
                </thead>
                <tbody class="">
                    @foreach (var item in Model.ResourceList)
                    {
                        <tr class="d-table-row">
                            <td class="d-table-cell">@item.Id</td>
                            <td class="d-table-cell">@item.Name</td>
                            <td class="d-table-cell">
                                <a asp-page-handler="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Clients/TAuth.ResourceClient/Pages/Logout.cshtml
@page
@model TAuth.ResourceClient.Pages.LogoutModel
@{
}

Clients/TAuth.ResourceClient/Pages/Profile.cshtml
@page
@model TAuth.ResourceClient.Pages.ProfileModel
@{
    ViewData["Title"] = "Profile";
}

<div class="text-center">
    <h1 class="display-4">Profile</h1>
</div>

<div class="container" id="user-profile">
    <div class="profile-name">@Model.FullName</div>
    <div class="profile-address text-info">
        @Model.Address
    </div>
</div>

Clients/TAuth.ResourceClient/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TAuth.ResourceClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TAuth.ResourceClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Profile">Profile</a>
                        </li>
                        @if (User.IsInRole(RoleNames.Administrator))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Admin">Admin</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item ml-auto">
                                <a class="btn btn-outline-danger" asp-area="" asp-page="/Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TAuth.ResourceClient - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>